<template>
  <div class="wrapper" ref="aaa">
    <ul class="content">
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
      <li>静候开发</li>
    </ul>
  </div>
</template>

<script>
  import BScroll from 'better-scroll'

  export default {
    name: "category",
    data() {
      return {
        scroll: null
      }
    },
    mounted() {
      this.scroll = new BScroll(document.querySelector('.wrapper'), {})
    }
  }
</script>

<style scoped>
  .wrapper {
    height: 800px;
    background-color: var(--color-tint);
    overflow: hidden;
  }
</style>
